### PR TITLE
Add support for Go 1.7

### LINKED ISSUE #162: Add Go 1.7 Support
Let's make sure we're following the latest Go releases, as @prashantv did in https://github.com/uber/tchannel-go/pull/428

### PR DESCRIPTION
**Pull request by breerly**
Fixes #162

### CODE REVIEW

**Comment by blampe** [comment]
:ship:

**Comment by breerly** [comment]
@abhinav @prashantv looks like `reflect.FuncOf` was removed in 1.7 - do you guys know where the docs are? Hoping there's an alternative - 

```
0.92s$ make test_ci
DEPRECATED Action signature.  Must be `cli.ActionFunc`.  This is an error in the application.  Please contact the distributor of this application if this is not you.  See https://github.com/urfave/cli/blob/master/CHANGELOG.md#deprecated-cli-app-action-signature
go build -i
# github.com/thriftrw/thriftrw-go/internal/curry
internal/curry/one.go:57: undefined: reflect.FuncOf
make: *** [build] Error 2
```

**Comment by breerly** [comment]
Hmmm.... looks like it still exists

https://tip.golang.org/pkg/reflect/#FuncOf

I guess there's another issue that isn't quite clear...

**Comment by breerly** [comment]
Ok - turns out you need to specify go versions available in `gimme` only.

There is a bug in Travis https://github.com/travis-ci/travis-ci/issues/6299 which runs the build as `1.5.1` if you choose a non-existent version. 

I've updated to use an existing version.

**Comment by abhinav** [comment]
lgtm

**Pull request merged**
